### ISSUE TITLE
Adding option to input own password ?

### ISSUE THREAD

**Issue by t3st3d** [cryptolok/SteCoSteg#3]
SteCoSteg could be used in combo with your other script EPMG, so that instead of writing somewhere the generated key, one could make something with EPMG and can retrieve the password of the image from anywhere, while still being secure. It adds portability and efficiency

**Comment by cryptolok** [comment]
well, you can always recover the key with the original image, unfortunately, I don't see how EPMG may come in handy since the image key is independent and inpredictable, I mean you can always encrypt the generated key with another one for more security (like AES), but if you can use encryption freely, you won't need steganography :) however, you can indeed use pseudo-randomly generated values as pixels in image, but such solution would probably lack security, which is the whole point of the project in the first place

**Comment by t3st3d** [comment]
I got your point, thanks. Why can we use the original image to recover the key ? Isn't that bad security-wise ? Sure if someone else wanted to get the thing inside the image, he would need to know that i used that script and find the original image, but still i don't see the utility of that feature ?

**Comment by cryptolok** [comment]
image recovery isn't a feature, but rather a bug :) it was not designed on purpose, it's just the way that the algorithme works, it can be used to retrieve the data without the key, which is more flexible for long keys, but at the same time weakens you in a case of investigation, but I offer the choice, of keeping the backup, or not
